const Map words = {
  "yes": "Yes",
  "no": "No",
  "clear_history": "Clear History",
  "check_clear_history": "Would you like to clear history records?",
  "roms": "ROMs",
  "history": "History",
  "plugins": "Plugins",
  "settings": "Settings",
  "select_rom": "Select Local Rom",
  "file_not_exist": "File not exist",
  "write_config": "Write RetroArch Configure",
  "check_write_config": "Would you like to install {0} as {1}",
  "libraries_hint": "Clone and select a project to main project, and enjoy!",
  "remove_project": "Remove Project",
  "would_remove_project": "Would you like to remove project({0})?",
  "new_project": "New Git project",
  "new_project_hint": "Git://...",
  "add": "Add",
  "search": "Search",
  "playlists_directory": "RetroArch Playlists Directory",
  "thumbnails_directory": "RetroArch Thumbnails Directory",
  "roms_directory": "ROMs Directory",
  "write_config_failed": "Write configure file failed!",
  "write_config_success": "Write configure file success!",
  "not_complete": "This ROM is not complete!",
  "framework": "Framework",
  "no_main_project": "None",
  "select_main_project_first": "Select a main project first",
  "cancel": "Cancel",
  "retry": "Retry",
  "retroarch": "RetroArch",
  "google_play": "Google Play",
  "official_website": "Official website",
  "webview": "WebView",
  "general": "General",
  "no_project_found": "Project not found!",
  "clone_base_framework": "Clone base framework",
  "index_select": "Select Collection",
  "install_confirm": "Clone project from {url}",
  "clone_project": "Cloning...",
  "after_select_main": "Already select {0} as main project.",
  "select_main_project": "Select as main project",
  "not_installed": "Not Cloned",
  "disclaimer": "Disclaimer",
  "disclaimer_content": """
This software is a software that loads a plug-in project provided by the developer to load network resources easily. The image resource text appearing in the software is provided by the plug-in project and the resource website.
The software itself does not provide comic services, please follow relevant laws and regulations when using video resources.

The copyright of the downloadable resources provided by this software belongs to the original author. It is for learning and communication purposes only. Please copy and download the files in accordance with relevant national laws and regulations, and do not use them for other purposes without the authorization of the copyright owner; if disputes arise due to illegal use, all consequences shall be borne by the user.
  """,
  "ok": "Ok",
  "open_retroarch": "Open RetroArch",
  "found_retroarch": "Found RetroArch {0}, would like open it?",
  "others": "Others",
};