const Map words = {
  "yes": "是",
  "no": "否",
  "clear_history": "抹除歷史",
  "check_clear_history": "是否要抹除歷史記錄?",
  "roms": "ROMs",
  "history": "羅縷紀存",
  "plugins": "插件管理",
  "settings": "詳設細定",
  "select_rom": "選擇本地ROM",
  "file_not_exist": "文件不存在",
  "write_config": "寫入RetroArch配置",
  "check_write_config": "是否把{0}作為{1}寫入RetroArch配置",
  "libraries_hint": "克隆然後選擇一個主要插件,即可愉快使用!",
  "remove_project": "移除項目",
  "would_remove_project": "是否將要移除項目({0})?",
  "new_project": "新Git項目",
  "new_project_hint": "Git://...",
  "add": "添加",
  "search": "尋幽覓勝",
  "playlists_directory": "RetroArch遊戲列表目錄",
  "thumbnails_directory": "RetroArch縮略圖目錄",
  "roms_directory": "ROMs目錄",
  "write_config_failed": "寫入配置失敗!",
  "write_config_success": "寫入配置成功!",
  "not_complete": "這個ROM文件沒有下載完成!",
  "framework": "Framework",
  "no_main_project": "None",
  "select_main_project_first": "請先選擇一個主要項目",
  "cancel": "取消",
  "retry": "重來",
  "retroarch": "RetroArch",
  "google_play": "Google Play",
  "official_website": "官方主頁",
  "webview": "瀏覽器",
  "general": "一般",
  "no_project_found": "沒有對應的項目!",
  "clone_base_framework": "克隆基礎庫",
  "index_select": "選擇分類",
  "install_confirm": "從 {url} 克隆項目",
  "clone_project": "克隆中...",
  "after_select_main": "已把 {0} 設置為主要項目.",
  "select_main_project": "選為主主要項目",
  "not_installed": "未克隆",
  "disclaimer": "免責聲明",
  "disclaimer_content": """
本軟件是個加載開發者提供的插件項目，來加載網絡資源的軟件。軟件中出現的圖片資源文字，都是由插件項目以及資源網站所提供。
軟件本身不提供視頻服務，使用漫畫資源時請遵循相關法律法規。

本軟件所提供下載的資源，版權歸原作者所有。僅供學習交流之用，請復制、下載者遵循國家相關法律、法規，在未獲得版權擁有者授權之前，勿作它用；如因非法使用引起糾紛，壹切後果由使用者承擔。
  """,
  "ok": "好",
  "open_retroarch": "啟動RetroArch",
  "found_retroarch": "探知到{0}, 是否打開?",
  "others": "其他",
};