const Map words = {
  "yes": "是",
  "no": "否",
  "clear_history": "抹除历史",
  "check_clear_history": "是否要抹除历史记录?",
  "roms": "ROMs",
  "history": "罗缕纪存",
  "plugins": "插件管理",
  "settings": "详设细定",
  "select_rom": "选择本地ROM",
  "file_not_exist": "文件不存在",
  "write_config": "写入RetroArch配置",
  "check_write_config": "是否把{0}作为{1}写入RetroArch配置",
  "libraries_hint": "克隆然后选择一个主要插件,即可愉快使用!",
  "remove_project": "移除项目",
  "would_remove_project": "是否将要移除项目({0})?",
  "new_project": "新Git项目",
  "new_project_hint": "Git://...",
  "add": "添加",
  "search": "寻幽觅胜",
  "playlists_directory": "RetroArch游戏列表目录",
  "thumbnails_directory": "RetroArch缩略图目录",
  "roms_directory": "ROMs目录",
  "write_config_failed": "写入配置失败!",
  "write_config_success": "写入配置成功!",
  "not_complete": "这个ROM文件没有下载完成!",
  "framework": "Framework",
  "no_main_project": "None",
  "select_main_project_first": "请先选择一个主要项目",
  "cancel": "取消",
  "retry": "重来",
  "retroarch": "RetroArch",
  "google_play": "Google Play",
  "official_website": "官方主页",
  "webview": "浏览器",
  "general": "一般",
  "no_project_found": "没有对应的项目!",
  "clone_base_framework": "克隆基础库",
  "index_select": "选择分类",
  "install_confirm": "从 {url} 克隆项目",
  "clone_project": "克隆中...",
  "after_select_main": "已把 {0} 设置为主要项目.",
  "select_main_project": "选为主主要项目",
  "not_installed": "未克隆",
  "disclaimer": "免责声明",
  "disclaimer_content": """
本软件是个加载开发者提供的插件项目，来加载网络资源的软件。软件中出现的图片资源文字，都是由插件项目以及资源网站所提供。
软件本身不提供视频服务，使用漫画资源时请遵循相关法律法规。

本软件所提供下载的资源，版权归原作者所有。仅供学习交流之用，请复制、下载者遵循国家相关法律、法规，在未获得版权拥有者授权之前，勿作它用；如因非法使用引起纠纷，一切后果由使用者承担。
  """,
  "ok": "好",
  "open_retroarch": "启动RetroArch",
  "found_retroarch": "探知到{0}, 是否打开?",
  "others": "其他",
};